config/routes.rb
Rails.application.routes.draw do
  root :to => 'quizzes#index'
  resources :quizzes do
    member do
      get :result
      get :image
      post :like, to: 'like#create'
    end
    collection do
      get :ranking
    end
  end
  resources :answer_choices
end

app/models/answer_choice.rb
class AnswerChoice < ApplicationRecord
  belongs_to :quiz
  belongs_to :choice

  scope :answer_count_sums, lambda {
    select_txt = <<~TEXT
      answer_choices.quiz_id,
      SUM(answer_choices.answer_count) as answer_count_sum,
      RANK() OVER (ORDER BY SUM(answer_choices.answer_count) DESC) as rank
    TEXT
    select(select_txt).group('quiz_id')
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :quiz
  has_one :answer_choice, dependent: :destroy

  validates :sentence, presence: true

  def answers_count
    answer_choice&.answer_count || 0
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :choices, dependent: :destroy
  has_many :answer_choices, dependent: :destroy
  has_one :like, dependent: :destroy
  accepts_nested_attributes_for :choices

  validates :title, presence: true
  validate :require_multi_choice
  validate :require_only_correct_choice, unless: -> { valid_choices.length < 2 }

  def correct_choice
    choices.select(&:correct).first
  end

  def self.ranking(num)
    count_sums = AnswerChoice.answer_count_sums.limit(num)
    quizzes = where(id: count_sums.map(&:quiz_id))
    quizzes = quizzes.map do |quiz|
      count_sum = count_sums.select { |r| r.quiz_id == quiz.id }.first
      { quiz: quiz, count_sum: count_sum.answer_count_sum, rank: count_sum.rank }
    end
    quizzes.sort_by { |quiz| quiz[:rank] }
  end

  def self.search(text)
    where('title LIKE :text OR body LIKE :text', text: "%#{text}%")
  end

  private

  def require_multi_choice
    errors.add(:choices, '選択肢は、2個以上指定してください') if valid_choices.length < 2
  end

  def require_only_correct_choice
    errors.add(:choices, '正解の選択肢は、1つ指定してください') if correct_choices.length != 1
  end

  def valid_choices
    choices.select(&:valid?)
  end

  def correct_choices
    choices.select(&:correct)
  end
end

app/models/quiz_image_helper.rb
class QuizImageHelper
  require 'mini_magick'
  require 'securerandom'

  BASE_IMAGE_PATH = './app/assets/images/bg_image.png'.freeze
  GRAVITY = 'center'.freeze
  TEXT_POSITION = '0,0'.freeze
  FONT = './app/assets/fonts/komorebi-gothic.ttf'.freeze
  FONT_SIZE = 65
  INDENTION_COUNT = 11
  ROW_LIMIT = 8

  class << self
    def build(text)
      text = prepare_text(text)
      @image = MiniMagick::Image.open(BASE_IMAGE_PATH)
      configuration(text)
    end

    def write(text)
      build(text)
      @image.write uniq_file_name
    end

    private

    def uniq_file_name
      "#{SecureRandom.hex}.png"
    end

    def configuration(text)
      @image.combine_options do |config|
        config.font FONT
        config.gravity GRAVITY
        config.pointsize FONT_SIZE
        config.draw "text #{TEXT_POSITION} '#{text}'"
      end
    end

    def prepare_text(text)
      text.scan(/.{1,#{INDENTION_COUNT}}/)[0...ROW_LIMIT].join("\n")
    end
  end
end

app/controllers/answer_choices_controller.rb
class AnswerChoicesController < ApplicationController
  def create
    @answer_choice = AnswerChoice.find_or_initialize_by(answer_choices_params)
    @answer_choice.answer_count += 1
    if @answer_choice.save
      redirect_to result_quiz_path(id: @answer_choice.quiz, answer_choice_id: @answer_choice.id)
    else
      redirect_to @answer_choice.quiz
    end
  end

  private

  def answer_choices_params
    params.require(:answer_choices).permit(:quiz_id, :choice_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def create
    @like = Like.find_or_initialize_by(quiz_id: params[:id])
    @like.like_count = likes_params[:value]
    @like.save!
  end

  private

  def likes_params
    params.require(:like).permit(:value)
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  MAX_CHOICES_COUNT = 4
  RANK_LIMIT = 10

  def index
    @quizzes = prepare_quizzes
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def result
    @quiz = Quiz.includes(choices: :answer_choice).find(params[:id])
    if params[:answer_choice_id].present?
      @user_choiced = AnswerChoice.find(params[:answer_choice_id]).choice
    else
      redirect_to @quiz
    end
  end

  def new
    @quiz = Quiz.new
    build_choices
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.choices = reject_blank_choices
    prepare_quiz_image
    if @quiz.save
      redirect_to quiz_path(@quiz)
    else
      build_choices
      render :new
    end
  end

  def edit
    @quiz = Quiz.find(params[:id])
    build_choices
  end

  def update
    @quiz = Quiz.find(params[:id])
    @quiz.attributes = quiz_params
    @quiz.choices = reject_blank_choices
    prepare_quiz_image
    if @quiz.save
      redirect_to quiz_path(@quiz)
    else
      build_choices
      render :edit
    end
  end

  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy
    redirect_to quizzes_path
  end

  def image
    @quiz = Quiz.find(params[:id])
    send_data @quiz.image, type: @quiz.ctype, disposition: 'inline'
  end

  def ranking
    @quiz_ranks = Quiz.ranking(RANK_LIMIT)
  end

  private

  def prepare_quizzes
    if params[:search_text]
      Quiz.includes(:choices, :like).search(params[:search_text])
    else
      Quiz.includes(:choices, :like)
    end.order(id: :desc)
  end

  def build_choices
    (MAX_CHOICES_COUNT - @quiz.choices.length).times { @quiz.choices.new }
  end

  def reject_blank_choices
    @quiz.choices.reject { |choice| choice.sentence.blank? }
  end

  def prepare_quiz_image
    quiz_image = QuizImageHelper.build(@quiz.body)
    @quiz.image = quiz_image.tempfile.open.read
    @quiz.ctype = quiz_image.mime_type
  end

  def quiz_params
    params.require(:quiz).permit(:title, :body, :explanation, choices_attributes: %i[id sentence correct])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitter_card_info(quiz)
    twitter_card = quiz ? quiz_show_card_info(quiz) : quiq_card_info
    twitter_card[:card] = 'summary_large_image'
    twitter_card[:site] = '@Madogiwa_Boy'
    twitter_card
  end

  private

  def quiz_show_card_info(quiz)
    {
      url: "https://quiz-quiq.herokuapp.com#{quiz_path(quiz)}",
      title: 'Quiz共有サービス QuiQ',
      description: quiz.body,
      image: "https://quiz-quiq.herokuapp.com#{image_quiz_path(quiz)}"
    }
  end

  def quiq_card_info
    {
      url: 'https://quiz-quiq.herokuapp.com/quizzes',
      title: 'Quiz共有サービス QuiQ',
      description: 'Quizを投稿して、すぐに共有、すぐに解答',
      image: 'https://raw.githubusercontent.com/Madogiwa0124/quiq/master/app/assets/images/top.png'
    }
  end
end

app/views/layouts/_error_form.html.haml
.alert.alert-danger{ role: 'alert' }
  - resource.errors.full_messages.each do |message|
    = message
    %br

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  = link_to 'QuiQ', quizzes_path, class: "navbar-brand"
  %button.navbar-toggler{ type:"button", 'data-toggle'=> "collapse", 'data-target' => "#navbarNav", 'aria-controls' => "navbarNav", 'aria-expanded' => "false", 'aria-label' => "Toggle navigation" }
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    %ul.navbar-nav.ml-auto
      %li.nav-item
        = render 'layouts/search_form'
      %li.nav-item.link
        = link_to ranking_quizzes_path do
          %i.fas.fa-crown
          Quizランキング
      %li.nav-item.link
        = link_to new_quiz_path do
          %i.fas.fa-plus
          Quizを投稿する

app/views/layouts/_search_form.html.haml
= form_with url: quizzes_path, method: :get, local: true, class: 'form-inline input-group' do |f|
  = f.text_field :search_text, class: 'form-control', value: params[:search_text]
  .input-group-append
    = f.button '検索', name: nil, type: :submit, class: 'btn btn-info'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QuiQ
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "https://use.fontawesome.com/releases/v5.1.1/css/all.css"
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1"}
    - twitter_card = twitter_card_info(@quiz&.id ? @quiz : nil)
    %meta{ name: "twitter:card", content: twitter_card[:card] }
    %meta{ name: "twitter:site", content: twitter_card[:site] }
    %meta{ property: "og:url", content: twitter_card[:url] }
    %meta{ property: "og:title", content: twitter_card[:title] }
    %meta{ property: "og:description", content: twitter_card[:description] }
    %meta{ property: "og:image", content: twitter_card[:image] }
  %body
    = render 'layouts/navbar'
    = yield
    %footer.bg-primary
      QuiQ
      %br
      Copyright &copy; Madogiwa_Boy All Rights Reserved

app/views/quizez/index.html.haml
%h1 Quiz一覧
= link_to '新規', new_quizez_path
%table{border: '1'}
  %thead
    %tr
      %th タイトル
      %th 本文
      %th アクション
  %tbody
    - @quizez.each do |quiz|
      %tr
        %td= quiz.title
        %td= quiz.body
        %td
          = link_to '編集', edit_quizez_path(quiz)
          = link_to '削除', quizez_path(quiz), method: :delete

app/views/quizzes/_choice_form.html.haml
%h6 選択肢
%spen ※２つ以上の選択肢を入力して、正解にチェックを入れてください。
= form_object.fields_for :choices do |choice|
  .input-group.mb-3
    .input-group-prepend
      .input-group-text
        = choice.check_box :correct
    = choice.text_field :sentence, class: 'form-control'

app/views/quizzes/_form.html.haml
= form_for @quiz do |f|
  - if @quiz.errors.any?
    = render 'layouts/error_form', resource: @quiz
  .form-group
    = f.label :title, 'タイトル'
    %br
    = f.text_field :title, class: 'form-control'
  .form-group  
    = f.label :body, '本文'
    %br
    = f.text_area :body, class: 'form-control'
  .form-group
    = f.label :explanation, '解説'
    %br
    = f.text_area :explanation, class: 'form-control'
  .form-group.choices_area
    = render 'choice_form', form_object: f
  = f.submit '投稿する', class: 'btn btn-primary'

app/views/quizzes/create.html.haml
%h1 Quizez#create
%p Find me in app/views/quizez/create.html.haml

app/views/quizzes/edit.html.haml
.container
  %h1 Quizの編集
  = render 'form'

app/views/quizzes/index.html.haml
#quiz-index
  .container
    = image_tag('top.png', style: 'max-width: 100%')
    .row
      - @quizzes.each do |quiz|
        .col-lg-4.card-space
          .card
            .card-header
              %div.quiz-title
                = quiz.title.truncate(13, omission: '…')
              %div.right
                %i.fas.fa-thumbs-up.text-info
                %span.text-secondary
                  = quiz.like.present? ? quiz.like.like_count : 0
            = image_tag(image_quiz_path(quiz), class: 'card-img-top', style: 'max-width: 100%')
            .card-body.center
              = link_to quiz_path(quiz), class: 'card-link' do
                %i.fas.fa-comment
                回答する

app/views/quizzes/new.html.haml
.container
  = render 'form'

app/views/quizzes/ranking.html.haml
#quiz-ranking
  .container
    = image_tag('top.png', style: 'max-width: 100%')
    %h3.center
      %i.fas.fa-crown
      解答数ランキング
    .row
      %ul.list-group
        - @quiz_ranks.each do |quiz_rank|
          %li.list-group-item
            %h5.text-primary
              %i.fas{ class: quiz_rank[:rank] < 4 ? 'fa-medal' : nil }
              %spen= "#{quiz_rank[:rank]}位"
              = quiz_rank[:quiz].title
            = quiz_rank[:quiz].body
            %p.right
              = link_to quiz_path(quiz_rank[:quiz]), class: 'card-link' do
                %i.fas.fa-comment
                回答する

app/views/quizzes/result.html.haml
#quiz_result
  .container
    .card.quiz_area
      .card-header= @quiz.title
      = image_tag(image_quiz_path(@quiz), class: 'card-img-top', style: 'max-width: 100%')
      .card-body
        - if @user_choiced.correct
          %p.text-danger.result_mark
            %span.correct ◯ 正解
        - else
          %p.text-primary.result_mark
            %span.uncorrect × 不正解
            %br
            = "正解は、#{@quiz.correct_choice.sentence}でした。"
        #share_area.center
          %tweet-button{ ':quiz_id': @quiz.id }
    .card
      .card-header 解説
      .card-body= @quiz.explanation
    .card
      .card-header 本文
      .card-body= @quiz.body
    .card
      .card-header 選択肢
      %ul.list-group.list-group-flush
        - @quiz.choices.each do |choice|
          %li.list-group-item
            - if choice == @user_choiced
              %span.text-danger= "#{choice.sentence}(あなたの解答)"
            - else
              %span= choice.sentence
            %span.badge.badge-primary.float-right= "#{choice.answers_count}人が回答"
    #like_area.center
      %p このQuizの評価してみませんか？🙌
      - like_count = @quiz.like.present? ? @quiz.like.like_count : 0
      %quiz-like{ ':init_like_count': like_count, ':quiz_id': @quiz.id }
= javascript_pack_tag 'quizzes'

app/views/quizzes/show.html.haml
#quiz-show
  .container
    .card
      .card-header= @quiz.title
      = image_tag(image_quiz_path(@quiz), class: 'card-img-top', style: 'max-width: 100%')
      .card-body= @quiz.body
    .card
      .card-header 選択肢
      %ul.list-group.list-group-flush
        - @quiz.choices.each do |choice|
          %li.list-group-item
            = link_to choice.sentence, answer_choices_path(answer_choices: { quiz_id: @quiz.id, choice_id: choice.id }), method: :post